# msys + mingw

NEST_INCLUDE = include
NEST_SOURCE = source
NEST_LIB = lib
GLEW_INCLUDE = GLEW/include
GLEW_LIB = GLEW/lib

all: 
	g++ -c $(NEST_SOURCE)/*.cpp -I$(NEST_INCLUDE) -I$(GLEW_INCLUDE)
	ar rvs $(NEST_LIB)/libnest.a *.o
	g++ -o $(NEST_LIB)/libnest.dll *.o \
		-L$(GLEW_LIB) -lGLEW32 -lOpenGL32 -m32 -shared
	-rm *.o
